# Generated by Django 5.1.5 on 2025-02-01 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_remove_message_sender_id_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='converation_owner',
        ),
        migrations.AddField(
            model_name='conversation',
            name='conversation_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
