# Generated by Django 5.1.5 on 2025-02-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_alter_user_password_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$870000$ekGusxKiHKNA8aVTyojPuz$jgz24784CsJnMxZ0XLLn/f6GPfhHGL7PW+aoqWYAAUg=', max_length=255),
        ),
    ]
