# Generated by Django 5.1.5 on 2025-02-04 22:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0011_remove_user_date_joined_alter_user_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$870000$ZwwxiBTJ34eVz6O4AVw7KF$r+CIScEwR4loCxHKufcdcVCXKyko7SAffOWIJMWLuH8=', max_length=255),
        ),
    ]
