# Generated by Django 5.1.5 on 2025-02-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_alter_user_created_at_alter_user_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$870000$Imb3AjnGwM8oSiyfnzq3jH$0+eMzSl/4mA+sZ55oDuuMigKApf98k4XmjaBShW3Ke8=', max_length=255),
        ),
    ]
