# Generated by Django 5.1.5 on 2025-02-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0013_alter_user_created_at_alter_user_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$870000$RUeKgMFdvz0KH5dJ8BGp74$i1jviAEi+3naoQhFKzHFUqFtZjXsNTuyUejuRjugqR8=', max_length=255),
        ),
    ]
