# Generated by Django 5.1.5 on 2025-02-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0014_alter_user_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$870000$T6KJ5kFUx7BlYb5FIvsC8c$g7BOhp0Y5JkRXBHa/19giZeA+0rtZGWNcKNRYOATn1k=', max_length=255),
        ),
    ]
