# Generated by Django 5.1.5 on 2025-02-04 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0015_alter_user_password_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_hash',
        ),
    ]
