# Generated by Django 5.1.5 on 2025-02-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0016_remove_user_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
