/*************  ✨ Codeium Command ⭐  *************/
version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=messaging_app
      - MYSQL_USER=messaging_app
      - MYSQL_PASSWORD=messaging_app
      - MYSQL_ROOT_PASSWORD=messaging_app
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=messaging_app.settings
volumes:
  dbdata:
/******  7068630c-ccf4-47a8-aa73-eb48161133c3  *******/
