apiVersion: apps/v1
kind: Deployment
metadata:
    name: django-messaging-app-green
spec:
    replicas: 3
    selector:
        matchLabels:
            app: django-messaging-app-green
    template:
        metadata:
            labels:
                app: django-messaging-app-green
        spec:
            containers:
                - name: django-messaging-app
                  image: your-docker-image:latest
                  ports:
                      - containerPort: 8000
